cache:
  directories:
    - $HOME/.composer/cache

language: php

sudo: false

dist: trusty

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly


before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls
